# Add-on configuration
name: "NestMTX"
version: "1.0.4"
slug: "nestmtx"
description: "Serve Nest camera streams as RTSP, HLS, or MJPEG"
url: "https://github.com/bitsbiter/home-assistant-addons/tree/main/nestmtx"
arch:
  - aarch64
init: true
map:
  - "share:rw"
ports:
  8554/tcp: 8554
  8555/tcp: 8555
  8556/tcp: 8556
ports_description:
  8554/tcp: "RTSP stream output"
  8555/tcp: "Web/HLS stream output"
  8556/tcp: "MJPEG stream output"
options:
  gcp_project_id: ""
  gcp_client_id: ""
  gcp_client_secret: ""
  gcp_token_path: "/share/nestmtx/google_token.json"
  stream_url: ""
schema:
  gcp_project_id: "str"
  gcp_client_id: "str"
  gcp_client_secret: "str"
  gcp_token_path: "str"
  stream_url: "str"